name: "Build/PullRequest"

on:
  push:
    branches: 
    - dev
    paths-ignore:
    - "**.md"
    - "**.spec.js"
    - ".idea"
    - ".vscode"
    - ".dockerignore"
    - "Dockerfile"
    - ".gitignore"
    - ".github/**"
    - "!.github/workflows/*.yml"

defaults:
  run:
    shell: "bash"

jobs:
  build:
    # see more environment https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: ["amd64", "arm64"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: "--max_old_space_size=6144"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Print uname
        run: uname -a

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Compile Electron app
        run: pnpm make
